### ISSUE TITLE
Discuss 0957+561 controversy 

### ISSUE THREAD

**Issue by dfm** [dfm/araa-gps#12]
Some references:

- [ ] https://ui.adsabs.harvard.edu/abs/1995ApJ...455L...5K/abstract
- [ ] https://ui.adsabs.harvard.edu/abs/1997ApJ...482...75K/abstract

**Comment by saigrain** [comment]
I've added a paragraph at the end of secion 1.2.2, not as concise as I'd like, but I hope it's ok. Feel free to comment or edit @dfm

**Comment by dfm** [comment]
I think this is great!
