### ISSUE TITLE
Different notation in Figure 5 than in the text

### ISSUE THREAD

**Issue by ericagol** [dfm/araa-gps#19]
The notation for the likelihood in figure 5 differs from that used in the text of the paper.

https://github.com/dfm/araa-gps/blob/a659c2ccdcbd30bacf6bb52e845f071ebae08a1f/src/tex/ms.tex#L334-L336

**Comment by saigrain** [comment]
I've updated the figure in google slides, but I don't know how to get the static figure into the right place within the github repo, so I'm going to leave that bit up to @dfm
