### ISSUE TITLE
Mean function missing?

### ISSUE THREAD

**Issue by ericagol** [dfm/araa-gps#20]
I'm wondering if the mean-function is missing from the equations in this paragraph:

https://github.com/dfm/araa-gps/blob/a659c2ccdcbd30bacf6bb52e845f071ebae08a1f/src/tex/ms.tex#L366-L373

or perhaps it would be easier to state at the start of the paragraph that this is for `m=0`?

**Comment by dfm** [comment]
Good point! I've added some text to clarify, but @saigrain should check.
