### ISSUE TITLE
Plots of kernel functions and power spectra

### ISSUE THREAD

**Issue by ericagol** [dfm/araa-gps#21]
It might be nice to make some plots of the kernel shapes and power spectra for the common kernels.

https://github.com/dfm/araa-gps/blob/a659c2ccdcbd30bacf6bb52e845f071ebae08a1f/src/tex/ms.tex#L482

Also, in footnote `d` of Table 1, perhaps mention that this is a "stochastically-driven damped simple harmonic oscillator"?

**Comment by dfm** [comment]
I've added the footnote, but I think we're going to skip adding the power spectra since we're already beyond our page limit!
