### ISSUE TITLE
Comparison of kernels - Figure 8

### ISSUE THREAD

**Issue by ericagol** [dfm/araa-gps#22]
I'm curious what value of `\gamma` was inferred for the Rational quadratic kernel as
this approaches the Squared Exponential kernel as `\gamma -> \infty`.   I find it interesting
that the Squared Exponential was so strongly preferred relative to the Matérn-3/2 given 
that these kernels look so similar.  The squared-exponential kernel decreases more steeply
at larger time separations, so I'm wondering if the better agreement of the squared exponential
is caused by the late data predictions which are poorer in the case of the Matern-3/2 since 
that kernel would cause the predicted data to continue trending in the same direction?  
It's also interesting that the Exponential Squared predicts a U-turn right at the end of the 
observed data - but maybe this is being drawn back by the mean?  What if the mean value is 
allowed to vary?  Would that give less preference for the squared exponential over Matern?

https://github.com/dfm/araa-gps/blob/a659c2ccdcbd30bacf6bb52e845f071ebae08a1f/src/tex/ms.tex#L707-L717

**Comment by dfm** [comment]
Here are the parameter inferences for the rational quadratic kernel:

![for-eric](https://user-images.githubusercontent.com/350282/201133581-a7d5ced8-ebb5-4af5-8e22-238c7e72b2bb.png)

>  What if the mean value is allowed to vary? Would that give less preference for the squared exponential over Matern?

Good question! We didn't experiment with this, but I will say that our results were not really sensitive to the random seed or how we chose to leave out the data, so I don't think that it is just luck of the draw that the differences are so strong!

**Comment by ericagol** [comment]
@dfm  Thanks for sharing that.  I'm still unclear on why the differences in Bayesian evidence between the first two kernels and the third is so strong...  and, FWIW, I think this would be good to understand this in order to give the reader a deeper intuition as to why these kernels can be distinguished.   I still suspect that the reason the Bayesian evidence is so similar for squared exponential & rational quadratic is that the kernels are probably _very_ similar.
