### ISSUE TITLE
Asteroseismology with PLATO

### ISSUE THREAD

**Issue by ericagol** [dfm/araa-gps#24]
My understanding is that the asteroseismic amplitude decreases sharply towards later
type stars, so I would be surprised if PLATO can characterize, say, M dwarfs with
asterorseismology (i.e. not "all" host stars, but perhaps most of the earlier types?).

https://github.com/dfm/araa-gps/blob/a659c2ccdcbd30bacf6bb52e845f071ebae08a1f/src/tex/ms.tex#L823

**Comment by dfm** [comment]
@saigrain — any thoughts about this?

**Comment by saigrain** [comment]
Good point, I've changed the text to make it clear that this sentence applies to the P1 sample (FGK stars with V<11);

For example, the \textit{PLATO} mission \citep{2014ExA....38..249R} aims to characterise most of the the host stars of the transiting planets it will discover up to magnitude $V \sim 11$ through asteroseismology (except for late K and M stars for which the oscillation amplitudes are too small and the frequencies too high).
