### ISSUE TITLE
Size of datasets?

### ISSUE THREAD

**Issue by ericagol** [dfm/araa-gps#28]
Perhaps it would be useful to comment on the size of datasets which GP analysis may be applied to?  If the dataset is too small, it might be difficult to learn the kernel hyperparameters and/or flag outliers.  If too large, then computational time might be too much of an issue for certain computations.

https://github.com/dfm/araa-gps/blob/a659c2ccdcbd30bacf6bb52e845f071ebae08a1f/src/tex/ms.tex#L988

**Comment by saigrain** [comment]
Added a sentence to that effect in section 7.1 (summary of the review):

Nonetheless, the size of the dataset remains an important consideration when deciding whether or not to use GPR for a particular problem. If too small, learning the kernel hyperparameters and flagging outliers can be difficult, while computing time can still be problematic for certain types of kernels and/or computations on very large datasets.
