### ISSUE TITLE
Hyper-parameter -> hyperparameter

### ISSUE THREAD

**Issue by dfm** [dfm/araa-gps#33]
In the literature, I think that [hyperparameter](https://en.wikipedia.org/wiki/Hyperparameter_(machine_learning)) is generally written without a hyphen. I propose that we switch to that here. What do you think, @saigrain?

**Comment by saigrain** [comment]
Agreed!

From: Dan Foreman-Mackey ***@***.***>
Sent: 19 October 2022 14:42
To: dfm/araa-gps ***@***.***>
Cc: Suzanne Aigrain ***@***.***>; Mention ***@***.***>
Subject: [dfm/araa-gps] Hyper-parameter -> hyperparameter (Issue #33)


In the literature, I think that hyperparameter<https://en.wikipedia.org/wiki/Hyperparameter_(machine_learning)> is generally written without a hyphen. I propose that we switch to that here. What do you think, @saigrain<https://github.com/saigrain>?

**Comment by dfm** [comment]
Great - done! Thanks.
